name: Deploy

on:
  push:
    branches:
      - source
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download Branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install NodeModules
        run: |
          rm -f .yarnclean yarn.lock
          yarn --non-interactive
          yarn list --depth=0

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Hexo Generate
        run: |
          rm -rf ./public
          yarn run hexo clean
          yarn run hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
          commit_message: "chore: deploy from ${{ github.repository }}@${{ github.sha }}"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"